### ISSUE TITLE
Creación de la Base de Datos con SQL (Fase 5)

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/cinem_extract_phyton_SQL#24]
Crear la base de datos con todas las tablas y la relación entre ellas. [DB diagram](https://app.diagrams.net/#G1Z8ettSlXo-RTpJZiJWQv6EEVmJvV4aAj#%7B%22pageId%22%3A%22g2XhwZLosCq4FbT1xWsN%22%7D).

**Criterios de aceptación de la tarea**:

- [x] Base de datos creada en MySQL Workbench
- [x] Tablas creadas en MySQL Workbench
- [x] Relaciones de tablas establecidas en MySQL Workbench

---------
Resultado de la tarea: [create_database.sql](https://github.com/carla-caracola/cinem_extract_phyton_SQL/blob/main/create_database.sql)

**Comment by carla-caracola** [comment]
@CecileSC  @BeaDataArtist , 

El script para crear la Base de Datos ya está listo: [create_database.sql](https://github.com/carla-caracola/cinem_extract_phyton_SQL/blob/main/create_database.sql) Tuve que hacer una modificación a la tabla intermedia que relaciona 'actor_details' con 'oscars' ya que el planteo que había sugerido era inconsistente. En lugar de ella, creé una tabla que se llama 'actor_awards' y 'actor_name' con 'ceremony_year' y 'award_type'.

He actualizado el [DB diagram](https://app.diagrams.net/#G1Z8ettSlXo-RTpJZiJWQv6EEVmJvV4aAj#%7B%22pageId%22%3A%22g2XhwZLosCq4FbT1xWsN%22%7D) acorde con los cambios. Algunos comentarios sobre mejoras que hice: 
- Agregué la referencia ON DELETE CASCADE y ON UPCATE CASCADE a todas las relaciones
- Agregué la referencia UNIQUE a algunas columnas como 'best_movie' en la tabla 'oscars' y 'name' en la tabla 'movies' que, si bien no son Primary Keys, son valores únicos que no deben repetirse. 
- A los tipos de datos que tienen opciones, como por ejemplo 'type' en  la tabla 'movies' que puede ser 'movie' o 'short', los indiqué como tipo ENUM indicando entre paréntesis las opciones posibles. Tengan en cuenta que tanto para el 'type' que acabo de mencionar como para el 'genre' indiqué todas las opciones posibles de la base de rapid api por si quisiéramos agregar otras categorías de datos para enriqueser nuestra base de datos. 


Creo que eso es todo. **Queda pendiente actualizar el archivo de python**. Crearé una nueva tarjeta para eso, asi puedo pasar esta a "review".

**Comment by BeaDataArtist** [comment]
Entiendo pues que ya solo queda pasarlo por phyton y si es posible que lo haga todo mediante una función, ¿cierto? ¡Muy buen trabajo @carla-caracola !

**Comment by carla-caracola** [comment]
@BeaDataArtist  si exacto!
