### ISSUE TITLE
Código Python para crear la base de datos (Fase 5)

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/cinem_extract_phyton_SQL#25]
Esta tarea es para crear el código en Python para crear la base de datos tablas y relaciones (en un Jupyter notebook) incorporando el script en SQL realizado en esta tarea https://github.com/carla-caracola/cinem_extract_phyton_SQL/issues/24.

**Criterios de aceptación**: 

- [x] Existe, en un Jupyter notebook, el código en Python para crear la base de datos de **cinem extract**, sus tablas y relaciones entre ellas.
- [x] El Jupyter notebook se encuentra en el repo del proyecto.
- [x] El código Python incorpora el script de SQL.
- [x] El código está hecho en funciones.

**Comment by BeaDataArtist** [comment]
He realizado un jypiter con funciones que crean la base de datos y sus tablas tal como ha diseñado @carla-caracola. Aún no lo meto en el proyecto hasta que os lo muestre mañana pero está realizado.
