### ISSUE TITLE
Extracción de Tablas de los Premios Oscar con Beautiful Soup (Fase 4)

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/cinem_extract_phyton_SQL#6]
Fase 4: Extracción de Tablas de los Premios Oscar con Beautiful Soup
En esta fase, trabajarán con la biblioteca Beautiful Soup para extraer información relevante de las tablas de los premios Oscar desde 2000. La tabla la encontrarás en el [este](https://es.wikipedia.org/wiki/Premios_%C3%93scar) link. La información que deberás sacar es:

Fecha de la ceremonia.

Mejor película.

Mejor director.

Mejor actor.

Mejor actriz.

NOTA: La información de la API deberá ser almacenada en una lista de tuplas. Cada tupla corresponderá a una película. Siguiendo el siguiente ejemplo:

`  [(1990, 'Driving Miss Daisy', 'O. Stone', "D. Day-Lewis",' J. Tandy' ),  ...]`

**Comment by carla-caracola** [comment]
Update de Bea en Slack: 

Terminado punto 4. Debo limpiarlo. Primero está la función sacando la tabla, y luego está otra vez la función pero con los resultados flitrados, Ahí quiero comentar luego un poco todo explicando bien lo que hace.

**Comment by carla-caracola** [comment]
Update de Bea: 

Progreso: 
- creación de la lista de tuplas

Pendiente:
- pasar los comentarios y nombres de funciones y procesos al inglés
- quitar el código repetido que ya me sobra

**Comment by BeaDataArtist** [comment]
Update:

- Finalizado en inglés y limpiado. Listo para review.
